//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public int A_id { get; set; }
        public string A_name { get; set; }
        public string A_address { get; set; }
        public Nullable<int> A_tel { get; set; }
        public string A_Email { get; set; }
    }
}
