//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [Required]
        [Display(Name = "C_id", ResourceType = typeof(Resource.CustomerResource))]
        public int? C_id { get; set; }

        [Required]
        [Display(Name = "C_pwd", ResourceType = typeof(Resource.CustomerResource))]
        public string C_pwd { get; set; }

   
        [Display(Name = "C_name", ResourceType = typeof(Resource.CustomerResource))]
        public string C_name { get; set; }

        [Display(Name = "C_sex", ResourceType = typeof(Resource.CustomerResource))]
        public string C_sex { get; set; }

     
        [Display(Name = "C_address", ResourceType = typeof(Resource.CustomerResource))]
        public string C_address { get; set; }

        [Required]
        [Display(Name = "C_tel", ResourceType = typeof(Resource.CustomerResource))]
        public int? C_tel { get; set; }

        [Display(Name = "C_email", ResourceType = typeof(Resource.CustomerResource))]
        public string C_email { get; set; }
    }
}
