//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datapay
    {
        public int p_id { get; set; }
        public Nullable<int> E_Id { get; set; }
        public Nullable<int> a_Id { get; set; }
        public Nullable<int> p_monney { get; set; }
        public Nullable<System.DateTime> p_dat { get; set; }
    }
}
