//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<ConfirmDetailPay> ConfirmDetailPays { get; set; }
        public virtual DbSet<Datapay> Datapays { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Pay> Pays { get; set; }
        public virtual DbSet<PaysupDetail> PaysupDetails { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<ReceiveProduct> ReceiveProducts { get; set; }
        public virtual DbSet<receiveProductType> receiveProductTypes { get; set; }
        public virtual DbSet<SaDataSaleDetaille> SaDataSaleDetailles { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<ScrapeDetail> ScrapeDetails { get; set; }
        public virtual DbSet<SentProduct> SentProducts { get; set; }
        public virtual DbSet<SentProductDetail> SentProductDetails { get; set; }
        public virtual DbSet<TakeGood> TakeGoods { get; set; }
        public virtual DbSet<TakeGoodsDetail> TakeGoodsDetails { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<UserLoging> UserLogings { get; set; }
    }
}
