//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public int P_id { get; set; }
        public Nullable<int> S_id { get; set; }
        public Nullable<int> C_id { get; set; }
        public Nullable<int> p_manney { get; set; }
        public Nullable<System.DateTime> p_Date { get; set; }
    }
}
