//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaysupDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaysupDetail()
        {
            this.PaysupDetail1 = new HashSet<PaysupDetail>();
        }
    
        public int pay_id { get; set; }
        public Nullable<int> Tak_id { get; set; }
        public Nullable<int> P_id { get; set; }
        public string Pro_name { get; set; }
        public Nullable<int> Pay_det_pricenum { get; set; }
        public Nullable<int> Pay_det_sum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaysupDetail> PaysupDetail1 { get; set; }
        public virtual PaysupDetail PaysupDetail2 { get; set; }
    }
}
