//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int P_id { get; set; }
        public string P_name { get; set; }
        public string P_Pic { get; set; }
        public string P_Detail { get; set; }
        public Nullable<int> P_Price { get; set; }
        public string P_Size { get; set; }
        public string P_Sale { get; set; }
        public string P_Weight { get; set; }
    }
}
