//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiveProduct
    {
        public int Re_pro_id { get; set; }
        public Nullable<int> E_id { get; set; }
        public Nullable<int> A_id { get; set; }
        public Nullable<int> Re_pro_net { get; set; }
        public Nullable<System.DateTime> Re_pro_date { get; set; }
    }
}
