//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int S_id { get; set; }
        public Nullable<int> E_id { get; set; }
        public Nullable<int> C_id { get; set; }
        public Nullable<int> S_net { get; set; }
        public Nullable<System.DateTime> S_date { get; set; }
        public Nullable<System.DateTime> Sd_pay { get; set; }
        public Nullable<System.DateTime> Sd_date { get; set; }
        public Nullable<int> Sd_amount { get; set; }
    }
}
