//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrapeDetail
    {
        public int Scrape_id { get; set; }
        public Nullable<int> P_id { get; set; }
        public Nullable<int> Scrape_amount { get; set; }
        public string Scrape_reason { get; set; }
    
        public virtual ScrapeDetail ScrapeDetail1 { get; set; }
        public virtual ScrapeDetail ScrapeDetail2 { get; set; }
    }
}
