//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentProductDetail
    {
        public int Sent_id { get; set; }
        public Nullable<int> P_id { get; set; }
        public Nullable<int> Pt_id { get; set; }
        public string Pro_name { get; set; }
        public Nullable<int> Sen_pro_number { get; set; }
        public Nullable<int> Sen_pro_total { get; set; }
    }
}
