//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentProduct
    {
        public int Sent_id { get; set; }
        public Nullable<int> A_Id { get; set; }
        public Nullable<int> C_id { get; set; }
        public Nullable<int> Tra_Total { get; set; }
        public string Sent_pay { get; set; }
        public Nullable<System.DateTime> Sent_Date { get; set; }
    }
}
